### Loading the dataset

In [8]:
import pandas as pd
import numpy as np

# Fix: Use the correct path to the dataset file
df = pd.read_csv('/home/deva_kush/ml_projects/CKD/data/kidney_disease.csv')

### Dataset Information

We use the following representation to collect the dataset
            age		-	age,	
			bp		-	blood pressure,
			sg		-	specific gravity,
			al		-   albumin,
			su		-	sugar,
			rbc		-	red blood cells,
			pc		-	pus cell,
			pcc		-	pus cell clumps,
			ba		-	bacteria,
			bgr		-	blood glucose random,
			bu		-	blood urea,
			sc		-	serum creatinine,
			sod		-	sodium,
			pot		-	potassium,
			hemo	-	hemoglobin,
			pcv		-	packed cell volume,
			wc		-	white blood cell count,
			rc		-	red blood cell count,
			htn		-	hypertension,
			dm		-	diabetes mellitus,
			cad		-	coronary artery disease,
			appet	-	appetite,
			pe		-	pedal edema,
			ane		-	anemia,
			class	-	class

In [9]:
# 3. Show basic info
print("📊 Dataset Shape:", df.shape)
print("\n🧾 Column Names:\n", df.columns.tolist())

# 4. Display first few rows
print("\n🔍 First 5 Rows:")
display(df.head())

# 5. Data types
print("\n📦 Data Types:")
print(df.dtypes)

df.describe()

📊 Dataset Shape: (300, 26)

🧾 Column Names:
 ['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']

🔍 First 5 Rows:


id   age     bp     sg   al   su       rbc        pc         pcc  \
0   99  56.0  180.0    NaN  0.0  4.0       NaN  abnormal  notpresent   
1  100  34.0   70.0  1.015  4.0  0.0  abnormal  abnormal  notpresent   
2  101  71.0   90.0  1.015  2.0  0.0       NaN  abnormal     present   
3  102  17.0   60.0  1.010  0.0  0.0       NaN    normal  notpresent   
4  103  76.0   70.0  1.015  2.0  0.0    normal  abnormal     present   

           ba  ...   pcv     wc   rc  htn   dm  cad  appet   pe  ane  \
0  notpresent  ...  32.0  10400  4.2  yes  yes   no   poor  yes   no   
1  notpresent  ...   NaN    NaN  NaN   no   no   no   good  yes   no   
2     present  ...  33.0  10700  3.9   no   no   no   good   no   no   
3  notpresent  ...  52.0   7000  NaN   no   no   no   good   no   no   
4  notpresent  ...  36.0  12700  4.2  yes   no   no   poor  yes  yes   

  classification  
0            ckd  
1            ckd  
2            ckd  
3            ckd  
4            ckd  

[5 rows x 26 columns]


📦 Data Types:
id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv               float64
wc                 object
rc                 object
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object


id         age          bp          sg          al          su  \
count  300.000000  293.000000  290.000000  267.000000  267.000000  265.000000   
mean   249.006667   49.972696   75.310345    1.018670    0.775281    0.373585   
std     87.180779   17.495575   13.621435    0.005399    1.298520    1.003809   
min     99.000000    2.000000   50.000000    1.005000    0.000000    0.000000   
25%    173.750000   39.000000   70.000000    1.015000    0.000000    0.000000   
50%    249.500000   52.000000   70.000000    1.020000    0.000000    0.000000   
75%    324.250000   63.000000   80.000000    1.025000    1.000000    0.000000   
max    399.000000   90.000000  180.000000    1.025000    5.000000    5.000000   

              bgr          bu          sc         sod         pot        hemo  \
count  273.000000  286.000000  287.000000  247.000000  247.000000  265.000000   
mean   141.098901   52.741958    2.591986  138.785425    4.551012   13.098113   
std     72.326627   47.755443    4.304881    6.806748    2.805741    2.878110   
min     22.000000    1.500000    0.400000  113.000000    2.500000    3.100000   
25%     99.000000   26.000000    0.800000  135.000000    3.800000   11.200000   
50%    118.000000   40.000000    1.200000  139.000000    4.400000   13.700000   
75%    140.000000   51.000000    2.200000  143.000000    4.900000   15.200000   
max    490.000000  322.000000   48.100000  150.000000   47.000000   17.800000   

              pcv  
count  256.000000  
mean    40.531250  
std      8.815706  
min      9.000000  
25%     35.000000  
50%     42.000000  
75%     48.000000  
max     54.000000

### Exploring the Data

In [10]:
print("\n❗ Missing Values Per Column:")
print(df.isnull().sum())

# 7. Check unique values of target column
if 'classification' in df.columns:
    print("\n🎯 Target Variable Distribution:")
    print(df['classification'].value_counts())
    




❗ Missing Values Per Column:
id                 0
age                7
bp                10
sg                33
al                33
su                35
rbc               96
pc                45
pcc                4
ba                 4
bgr               27
bu                14
sc                13
sod               53
pot               53
hemo              35
pcv               44
wc                66
rc                87
htn                2
dm                 2
cad                2
appet              1
pe                 1
ane                1
classification     0
dtype: int64

🎯 Target Variable Distribution:
classification
notckd    150
ckd       149
ckd\t       1
Name: count, dtype: int64


### Cleaning


In [11]:
df = df.drop(columns=['id'])
df['classification'] = df['classification'].str.strip()
df = df.replace('?', np.nan)

for col in ['pcv', 'wc', 'rc']:
    df[col] = pd.to_numeric(df[col], errors='coerce')


binary_map = {'yes': 1, 'no': 0, 'present': 1, 'notpresent': 0, 'good': 1, 'poor': 0}
for col in ['htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'pcc', 'ba']:
    df[col] = df[col].map(binary_map)

df['classification'] = df['classification'].map({'ckd': 1, 'notckd': 0})


df['rbc'] = df['rbc'].map({'normal': 1, 'abnormal': 0})
df['pc'] = df['pc'].map({'normal': 1, 'abnormal': 0})

# Check again for nulls
print("🧼 Nulls After Cleaning:")
print(df.isnull().sum())


🧼 Nulls After Cleaning:
age                7
bp                10
sg                33
al                33
su                35
rbc               96
pc                45
pcc                4
ba                 4
bgr               27
bu                14
sc                13
sod               53
pot               53
hemo              35
pcv               44
wc                67
rc                88
htn                2
dm                 5
cad                2
appet              1
pe                 1
ane                1
classification     0
dtype: int64


### Handling Missing Values

In [12]:
num_cols = ['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

cat_cols = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])


print("✅ Nulls Remaining (Post-Imputation):")
print(df.isnull().sum().sum())  





✅ Nulls Remaining (Post-Imputation):
0


### Feature Scaling


In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Extract features and target
X = df.drop(columns=['classification'])
y = df['classification']

# Identify numeric columns
numeric_cols = X.select_dtypes(include=['float64', 'int64']).columns

# 80-20 split with stratification (to preserve class balance)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Apply Standard Scaling - CORRECT WAY
scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

print("✅ Final Data Shape:", X.shape)
print("✅ Target Class Balance:\n", y.value_counts())



✅ Final Data Shape: (300, 24)
✅ Target Class Balance:
 classification
1    150
0    150
Name: count, dtype: int64


### Train-Test Split & Baseline Model

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Train
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("🎯 Accuracy:", accuracy_score(y_test, y_pred))
print("🧾 Classification Report:\n", classification_report(y_test, y_pred))
print("🧩 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


### Comparing Multiple Models


In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

models = {
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier(),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"🔹 {name} Accuracy: {acc:.4f}")


🔹 Decision Tree Accuracy: 1.0000
🔹 Random Forest Accuracy: 1.0000
🔹 SVM Accuracy: 1.0000
🔹 KNN Accuracy: 0.9500


/home/deva_kush/anaconda3/envs/ai-env/lib/python3.11/site-packages/xgboost/training.py:183: UserWarning: [18:31:35] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


🔹 XGBoost Accuracy: 0.9667


### Validate Random Forest with Cross-Validation

In [15]:
from sklearn.model_selection import cross_val_score

rf = RandomForestClassifier()
cv_scores = cross_val_score(rf, X, y, cv=5)
print("Cross-Val Accuracy: ", cv_scores.mean())


Cross-Val Accuracy:  1.0


### Feature Importance

In [16]:
rf.fit(X_train, y_train)
importances = rf.feature_importances_
feature_names = X.columns

importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Plot
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
sns.barplot(x='Importance', y='Feature', data=importance_df.head(10))
plt.title("Top 10 Important Features")
plt.show()


### Saving Model

In [19]:
import joblib

# Save the model and any preprocessing pipeline if used
joblib.dump(rf, 'ckd_model.pkl')

joblib.dump(scaler, 'scaler.pkl')
# No encoder was used, so nothing to save for encoder


['scaler.pkl']

In [20]:
healthy = {
    'age': 35, 'bp': 70, 'sg': 1.025, 'al': 0, 'su': 0,
    'rbc': 1, 'pc': 1, 'pcc': 0, 'ba': 0, 'bgr': 99,
    'bu': 20, 'sc': 1.0, 'sod': 138, 'pot': 4.2,
    'hemo': 15.0, 'pcv': 42, 'wc': 7500, 'rc': 5.0,
    'htn': 0, 'dm': 0, 'cad': 0, 'appet': 1, 'pe': 0, 'ane': 0
}
early_ckd = {
    'age': 55, 'bp': 85, 'sg': 1.015, 'al': 2, 'su': 1,
    'rbc': 0, 'pc': 0, 'pcc': 0, 'ba': 0, 'bgr': 160,
    'bu': 55, 'sc': 2.0, 'sod': 132, 'pot': 4.8,
    'hemo': 10.5, 'pcv': 34, 'wc': 9800, 'rc': 3.8,
    'htn': 1, 'dm': 1, 'cad': 0, 'appet': 1, 'pe': 0, 'ane': 1
}
late_ckd = {
    'age': 70, 'bp': 95, 'sg': 1.005, 'al': 4, 'su': 3,
    'rbc': 0, 'pc': 0, 'pcc': 1, 'ba': 1, 'bgr': 250,
    'bu': 130, 'sc': 5.8, 'sod': 128, 'pot': 6.2,
    'hemo': 7.8, 'pcv': 25, 'wc': 11000, 'rc': 2.6,
    'htn': 1, 'dm': 1, 'cad': 1, 'appet': 0, 'pe': 1, 'ane': 1
}
diabetic_no_ckd = {
    'age': 45, 'bp': 75, 'sg': 1.020, 'al': 0, 'su': 0,
    'rbc': 1, 'pc': 1, 'pcc': 0, 'ba': 0, 'bgr': 180,
    'bu': 28, 'sc': 1.1, 'sod': 139, 'pot': 4.1,
    'hemo': 13.5, 'pcv': 41, 'wc': 7600, 'rc': 4.9,
    'htn': 0, 'dm': 1, 'cad': 0, 'appet': 1, 'pe': 0, 'ane': 0
}


In [27]:
import pandas as pd

xg = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xg.fit(X_train, y_train)

test_df = pd.DataFrame([healthy, early_ckd, late_ckd, diabetic_no_ckd])
predictions = xg.predict(test_df)

print(predictions)  # Output like: [0, 1, 1, 0, 1]


/home/deva_kush/anaconda3/envs/ai-env/lib/python3.11/site-packages/xgboost/training.py:183: UserWarning: [19:26:17] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[0 1 1 0]


In [34]:
import joblib

# Save the model and any preprocessing pipeline if used
joblib.dump(rf, 'ckd_xgb_model.pkl')

['ckd_xgb_model.pkl']

In [28]:
test_df = pd.DataFrame([healthy, early_ckd, late_ckd, diabetic_no_ckd])
predictions = rf.predict(test_df)

print(predictions)

[1 1 1 1]


In [32]:
import pandas as pd

kn = KNeighborsClassifier()
kn.fit(X_train, y_train)

test_df = pd.DataFrame([healthy, early_ckd, late_ckd, diabetic_no_ckd])
predictions = kn.predict(test_df)

print(predictions)

[1 1 1 1]
